name: GraphBacktracking
version: "0.3.0"
date: 2019-11-07
description: |
    Super Secret Awesome Searching

authors:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Wilf Wilson
      url: http://wilf.me

maintainers:
    - name: Christopher Jefferson
      url: http://caj.host.cs.st-andrews.ac.uk/
    - name: Wilf Wilson
      url: http://wilf.me

GAP: ">= 4.9"

needed-pkgs:
    - name: "BacktrackKit"
      version: ">= 0.3"
      url: "https://peal.github.io/BacktrackKit/"
    - name: "digraphs"
      version: ">= 1.0.0"
      url: "https://gap-packages.github.io/Digraphs"

www: https://peal.github.io/GraphBacktracking/
readme: README.md
packageinfo: https://peal.github.io/GraphBacktracking/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/peal/GraphBacktracking/releases/download/v0.3.0/GraphBacktracking-0.3.0.tar.gz

abstract: |

status: dev
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>JW19</span>]   <b class='BibAuthor'>Jefferson, C. and Wilson, W.</b>,
     <i class='BibTitle'>GraphBacktracking, Super Secret Awesome Searching,
             Version 0.3.0</i>
     (<span class='BibYear'>2019</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://peal.github.io/GraphBacktracking/">https://peal.github.io/GraphBacktracking/</a></span>.
    </p>
    

bibtex: |
    @misc{ GraphBacktracking0.3.0,
      author =           {Jefferson, C. and Wilson, W.},
      title =            {{GraphBacktracking},  Super  Secret Awesome Searching,
                          {V}ersion 0.3.0},
      month =            {Nov},
      year =             {2019},
      note =             {GAP package},
      howpublished =     {\href      {https://peal.github.io/GraphBacktracking/}
                          {\texttt{https://peal.github.io/}\discretionary
                          {}{}{}\texttt{GraphBacktracking/}}},
      printedkey =       {JW19}
    }

